### PR TITLE
Added overload for [] operator to inipp.h and modified example.cpp to…

### PR DESCRIPTION
**Pull request by jamesBrosnahan**
… use the [] operator instead of .sections; I know that this is a simple addition but, it helps move the code towards functioning more like an STL container.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Thank you so much for your kind contribution, James.

When designing the Ini class, I considered carefully whether to go for composition (as in the current design), or whether to inherit from std::map. After doing quite a bit of research and testing, I found that the std containers aren't meant for subclassing, whence the current design. (For instance, see https://stackoverflow.com/questions/6806173/subclass-inherit-standard-containers ) So yes, it is intentionally not behaving like an STL container.

Therefore, .sections is what you use to get the container behaviour, and keep the Ini class to parsing and generating. I think I will keep this design, as it is simple and transparent, and not "upgrade" the Ini class to exhibit container like behaviour, as this is already fully exposed via .sections. Adding the operator you suggest might create an expectation that the Ini class is, as you say, functioning as an STL container. That isn't meant to be.

I'm sorry if it comes as a disappointment that I will not accept your patch, but I hope the reasoning above explains this decision.

**Comment by jamesBrosnahan** [comment]
Thanks for reviewing the code. Composition makes it feel like the parsing functions of the inipp class could be made static 

I want to know what your opinion is on using std::any as return type for a function that parses the string values in the section map, [does ini have a limited set of data types]? It's to implement something like this : [convert-string-to-variable-name-or-variable-type](https://stackoverflow.com/questions/7143120/convert-string-to-variable-name-or-variable-type) but is part of c++17 so it would need a macro to prevent errors from compilers using a standard before c++17 [how-to-determine-the-version-of-the-c-standard-used-by-the-compiler](https://stackoverflow.com/questions/2324658/how-to-determine-the-version-of-the-c-standard-used-by-the-compiler)

**Comment by mcmtroffaes** [comment]
You're correct: the parse, generate, default_section, and interpolate functions could have been static methods and the sections and errors fields could have been removed from the class entirely, with the class just statically representing the formatting details of the ini file.

On your other question, yes, ofc in principle, you could store values in a std::any container. Would that make sense in general? Maybe not. But there might be situations where it would make sense, if you have a field in your ini file that does not have a fixed type in advance. Either way, you would still have to convert the string values to specific C++ types before storing them inside a std::any. I'd expect you normally would fix the type of every value in the standard use case for ini files; your code will look a lot simpler if you can make this assumption.

On your other question, ini files have no awareness of data types. Everything is just a text string.

I hope this helps.

**Comment by jamesBrosnahan** [comment]
Thank you that helps.

**Pull request closed without merging**
