### PR TITLE
Merge local 'refactor' branch into local 'develop' and merge into 'origin/develop'

### PR DESCRIPTION
**Pull request by GermanAizek**
Forgot to immediately merge branch in `develop`

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Unless I'm missing something, this patch was already merged: there's no need for another PR. Or am I missing something?

**Comment by mcmtroffaes** [comment]
... and I just double checked, develop is in sync with this patch; closing.

**Comment by GermanAizek** [comment]
@mcmtroffaes,
Clone your repository, allright.

**Comment by mcmtroffaes** [comment]
You don't need to reclone it - just rebase your develop branch onto upstream (i.e. this one) and you should be good to go.

https://git-scm.com/docs/git-rebase

I assume you're new at git- good luck learning it! It can all be a bit confusing at first.

**Pull request closed without merging**
